### PR TITLE
Add support for Azure, OpenAI, Palm, Anthropic, Cohere Models - using litellm

### PR DESCRIPTION
**Pull request by ishaan-jaff**
I'm the maintainer of litellm https://github.com/BerriAI/litellm - a simple & light package to call OpenAI, Azure, Cohere, Anthropic API Endpoints

This PR adds support for models from all the above mentioned providers

Here's a sample of how it's used:

```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
cc @jamesturk

**Comment by jamesturk** [comment]
Hey, this looks like a really great way to do this.  I'm curious about other changes that'll need to be made though, presumably the other places that use `openai` directly (exceptions/etc.) need to be modified to preserve expected behavior.

Glad to take a closer look soon, or if you have time that'd be great too!

Either way, thanks for this!

**Comment by ishaan-jaff** [comment]
Hi @jamesturk thanks for the prompt response. 

As for using litellm - we send the OpenAI exceptions etc back to you. Outputs/Exceptions are exactly what OpenAI sends you
 
Adding a link to our docs for your convenience: [litellm.readthedocs.io/en/latest/](https://litellm.readthedocs.io/en/latest/)

I took a look at scrapeghost afaik it looks like `apicall.py` is the only place calling `chatCompletion.create`

**Comment by jamesturk** [comment]
As stated: to get this working, we'd need to handle all of the different exceptions appropriately. If someone wants to pick that up I'd be glad to work with them on that, but going to close this PR as it stands as I don't think we'll be using litellm, probably https://llm.datasette.io/en/stable/ instead.

**Pull request closed without merging**
